name: "Github Actions Pragmatic Programmer Bot"

on:
  push:
  schedule:
    - cron: '0 07 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      #- run: npm install
      - name: Run python
        run: python3 bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
