name: "Github Actions Pragmatic Programmer Bot"

on:
  push:
  schedule:
    - cron: '0 07 * * *'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: pip3 install -r requirements.txt
      - name: Run python
        run: python3 bot.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
